# coding: utf-8

"""
    Flagr

    Flagr is a feature flagging, A/B testing and dynamic configuration microservice. The base path for all the APIs is \"/api/v1\".   # noqa: E501

    OpenAPI spec version: 1.1.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import flagr
from flagr.models.health import Health  # noqa: E501
from flagr.rest import ApiException


class TestHealth(unittest.TestCase):
    """Health unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHealth(self):
        """Test Health"""
        # FIXME: construct object with mandatory attributes with example values
        # model = flagr.models.health.Health()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
