# coding: utf-8

"""
    Flagr

    Flagr is a feature flagging, A/B testing and dynamic configuration microservice  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import flagr
from flagr.api.distribution_api import DistributionApi  # noqa: E501
from flagr.rest import ApiException


class TestDistributionApi(unittest.TestCase):
    """DistributionApi unit test stubs"""

    def setUp(self):
        self.api = flagr.api.distribution_api.DistributionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_find_distributions(self):
        """Test case for find_distributions

        """
        pass

    def test_put_distributions(self):
        """Test case for put_distributions

        """
        pass


if __name__ == '__main__':
    unittest.main()
