# coding: utf-8

"""
    Flagr

    Flagr is a feature flagging, A/B testing and dynamic configuration microservice  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import flagr
from flagr.models.create_variant_request import CreateVariantRequest  # noqa: E501
from flagr.rest import ApiException


class TestCreateVariantRequest(unittest.TestCase):
    """CreateVariantRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateVariantRequest(self):
        """Test CreateVariantRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = flagr.models.create_variant_request.CreateVariantRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
