# coding: utf-8

"""
    Flagr

    Flagr is a feature flagging, A/B testing and dynamic configuration microservice. The base path for all the APIs is \"/api/v1\".   # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import flagr
from flagr.api.export_api import ExportApi  # noqa: E501
from flagr.rest import ApiException


class TestExportApi(unittest.TestCase):
    """ExportApi unit test stubs"""

    def setUp(self):
        self.api = flagr.api.export_api.ExportApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_export_sq_lite(self):
        """Test case for get_export_sq_lite

        """
        pass


if __name__ == '__main__':
    unittest.main()
