# coding: utf-8

"""
    Flagr

    Flagr is a feature flagging, A/B testing and dynamic configuration microservice  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import flagr
from flagr.api.segment_api import SegmentApi  # noqa: E501
from flagr.rest import ApiException


class TestSegmentApi(unittest.TestCase):
    """SegmentApi unit test stubs"""

    def setUp(self):
        self.api = flagr.api.segment_api.SegmentApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_segment(self):
        """Test case for create_segment

        """
        pass

    def test_delete_segment(self):
        """Test case for delete_segment

        """
        pass

    def test_find_segments(self):
        """Test case for find_segments

        """
        pass

    def test_put_segment(self):
        """Test case for put_segment

        """
        pass

    def test_put_segments_reorder(self):
        """Test case for put_segments_reorder

        """
        pass


if __name__ == '__main__':
    unittest.main()
