# coding: utf-8

"""
    Flagr

    Flagr is a feature flagging, A/B testing and dynamic configuration microservice. The base path for all the APIs is \"/api/v1\".   # noqa: E501

    OpenAPI spec version: 1.1.10
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import flagr
from flagr.api.tag_api import TagApi  # noqa: E501
from flagr.rest import ApiException


class TestTagApi(unittest.TestCase):
    """TagApi unit test stubs"""

    def setUp(self):
        self.api = flagr.api.tag_api.TagApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_tag(self):
        """Test case for create_tag

        """
        pass

    def test_delete_tag(self):
        """Test case for delete_tag

        """
        pass

    def test_find_all_tags(self):
        """Test case for find_all_tags

        """
        pass

    def test_find_tags(self):
        """Test case for find_tags

        """
        pass


if __name__ == '__main__':
    unittest.main()
