# coding: utf-8

"""
    Flagr

    Flagr is a feature flagging, A/B testing and dynamic configuration microservice  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import flagr
from flagr.api.variant_api import VariantApi  # noqa: E501
from flagr.rest import ApiException


class TestVariantApi(unittest.TestCase):
    """VariantApi unit test stubs"""

    def setUp(self):
        self.api = flagr.api.variant_api.VariantApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_variant(self):
        """Test case for create_variant

        """
        pass

    def test_delete_variant(self):
        """Test case for delete_variant

        """
        pass

    def test_find_variants(self):
        """Test case for find_variants

        """
        pass

    def test_put_variant(self):
        """Test case for put_variant

        """
        pass


if __name__ == '__main__':
    unittest.main()
