# coding: utf-8

# flake8: noqa

"""
    Flagr

    Flagr is a feature flagging, A/B testing and dynamic configuration microservice. The base path for all the APIs is \"/api/v1\".   # noqa: E501

    OpenAPI spec version: 1.1.10
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from flagr.api.constraint_api import ConstraintApi
from flagr.api.distribution_api import DistributionApi
from flagr.api.evaluation_api import EvaluationApi
from flagr.api.export_api import ExportApi
from flagr.api.flag_api import FlagApi
from flagr.api.health_api import HealthApi
from flagr.api.segment_api import SegmentApi
from flagr.api.tag_api import TagApi
from flagr.api.variant_api import VariantApi

# import ApiClient
from flagr.api_client import ApiClient
from flagr.configuration import Configuration
# import models into sdk package
from flagr.models.constraint import Constraint
from flagr.models.create_constraint_request import CreateConstraintRequest
from flagr.models.create_flag_request import CreateFlagRequest
from flagr.models.create_segment_request import CreateSegmentRequest
from flagr.models.create_tag_request import CreateTagRequest
from flagr.models.create_variant_request import CreateVariantRequest
from flagr.models.distribution import Distribution
from flagr.models.error import Error
from flagr.models.eval_context import EvalContext
from flagr.models.eval_debug_log import EvalDebugLog
from flagr.models.eval_result import EvalResult
from flagr.models.evaluation_batch_request import EvaluationBatchRequest
from flagr.models.evaluation_batch_response import EvaluationBatchResponse
from flagr.models.evaluation_entity import EvaluationEntity
from flagr.models.flag import Flag
from flagr.models.flag_snapshot import FlagSnapshot
from flagr.models.health import Health
from flagr.models.put_distributions_request import PutDistributionsRequest
from flagr.models.put_flag_request import PutFlagRequest
from flagr.models.put_segment_reorder_request import PutSegmentReorderRequest
from flagr.models.put_segment_request import PutSegmentRequest
from flagr.models.put_variant_request import PutVariantRequest
from flagr.models.segment import Segment
from flagr.models.segment_debug_log import SegmentDebugLog
from flagr.models.set_flag_enabled_request import SetFlagEnabledRequest
from flagr.models.tag import Tag
from flagr.models.variant import Variant
