# coding: utf-8

"""
    Flagr

    Flagr is a feature flagging, A/B testing and dynamic configuration microservice. The base path for all the APIs is \"/api/v1\".   # noqa: E501

    OpenAPI spec version: 1.1.10
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class CreateFlagRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'description': 'str',
        'key': 'str',
        'template': 'str'
    }

    attribute_map = {
        'description': 'description',
        'key': 'key',
        'template': 'template'
    }

    def __init__(self, description=None, key=None, template=None):  # noqa: E501
        """CreateFlagRequest - a model defined in Swagger"""  # noqa: E501

        self._description = None
        self._key = None
        self._template = None
        self.discriminator = None

        self.description = description
        if key is not None:
            self.key = key
        if template is not None:
            self.template = template

    @property
    def description(self):
        """Gets the description of this CreateFlagRequest.  # noqa: E501


        :return: The description of this CreateFlagRequest.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this CreateFlagRequest.


        :param description: The description of this CreateFlagRequest.  # noqa: E501
        :type: str
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501
        if description is not None and len(description) < 1:
            raise ValueError("Invalid value for `description`, length must be greater than or equal to `1`")  # noqa: E501

        self._description = description

    @property
    def key(self):
        """Gets the key of this CreateFlagRequest.  # noqa: E501

        unique key representation of the flag  # noqa: E501

        :return: The key of this CreateFlagRequest.  # noqa: E501
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key):
        """Sets the key of this CreateFlagRequest.

        unique key representation of the flag  # noqa: E501

        :param key: The key of this CreateFlagRequest.  # noqa: E501
        :type: str
        """

        self._key = key

    @property
    def template(self):
        """Gets the template of this CreateFlagRequest.  # noqa: E501

        template for flag creation  # noqa: E501

        :return: The template of this CreateFlagRequest.  # noqa: E501
        :rtype: str
        """
        return self._template

    @template.setter
    def template(self, template):
        """Sets the template of this CreateFlagRequest.

        template for flag creation  # noqa: E501

        :param template: The template of this CreateFlagRequest.  # noqa: E501
        :type: str
        """

        self._template = template

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreateFlagRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateFlagRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
